version: "3.5"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    restart: unless-stopped
    environment:
      SA_PASSWORD: "password123Admin789"
      ACCEPT_EULA: "Y"
    ports:
       - "1433:1433"
    networks:
       - testnetwork
  
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 52841:80
    networks:
      - testnetwork
    depends_on:
      - sqlserver

networks:
  testnetwork:
    name: test-network
